version: '3.7'
services:
  mini-post-database-service:
    image: postgres:13
    container_name: mini-post-database-postgres
    ports:
      - '${DATABASE_PORT}:5432'
    networks:
      - mini-post-net
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD} # TODO: create new roles for dev and test
    volumes:
      - mini-post-database-postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mini-post-caching-service:
    image: 'redis:latest'
    container_name: mini-post-caching-redis
    hostname: redis
    networks:
      - mini-post-net
    ports:
      - '${CACHING_PORT}:6379'
    command: '--requirepass ${CACHING_PASSWORD}'
    volumes:
      - mini-post-caching-redis-volume:/data
    restart: unless-stopped

  mini-post-backend-service:
    container_name: mini-post-server-nestjs
    build:
      context: ./
    ports:
      - '${SERVER_HTTP_PORT}:${SERVER_HTTP_PORT}'
      - '${SERVER_SOCKET_PORT}:${SERVER_SOCKET_PORT}'
    networks:
      - mini-post-net
    depends_on:
      - mini-post-database-service
      - mini-post-caching-service
    restart: unless-stopped

volumes:
  mini-post-database-postgres_data:
  mini-post-caching-redis-volume:

networks:
  mini-post-net:
    driver: bridge
